server:
  port: 7900
spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.github.xiaoxfan: DEBUG

